NetworkStack:
  name: NetworkStack
  template: NetworkStack.json
  require: ~
  parameters:
    VPCName: myVPC
WebAppStack:
  name: WebAppStack
  template: WebAppStack.json
  require: NetworkStack
  parameters:
     NetworkStackName: NetworkStack
     InstanceName: WebApp1
     SomeParameter: SomeValue